<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261001151525 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajout des entités Membership et MembershipFee pour le système d\'adhésion';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE membership_fees (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, amount INT NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, effective_from TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, notes TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE memberships (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_active BOOLEAN NOT NULL, started_at DATE NOT NULL, expires_at DATE NOT NULL, amount INT NOT NULL, stripe_payment_id VARCHAR(255) DEFAULT NULL, renewed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, reminder_sent_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_865A4776A76ED395 ON memberships (user_id)');
        $this->addSql('ALTER TABLE memberships ADD CONSTRAINT FK_865A4776A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD requested_function VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD is_registration_confirmed BOOLEAN NOT NULL DEFAULT false');
        $this->addSql('ALTER TABLE "user" ADD registration_validated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE memberships DROP CONSTRAINT FK_865A4776A76ED395');
        $this->addSql('DROP TABLE membership_fees');
        $this->addSql('DROP TABLE memberships');
        $this->addSql('ALTER TABLE "user" DROP requested_function');
        $this->addSql('ALTER TABLE "user" DROP is_registration_confirmed');
        $this->addSql('ALTER TABLE "user" DROP registration_validated_at');
    }
}
