<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20261001075246 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE blog_post (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_published BOOLEAN NOT NULL, image VARCHAR(255) DEFAULT NULL, author_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BA5AE01DF675F31B ON blog_post (author_id)');
        $this->addSql('CREATE TABLE blog_post_gallery_image (blog_post_id INT NOT NULL, gallery_image_id INT NOT NULL, PRIMARY KEY (blog_post_id, gallery_image_id))');
        $this->addSql('CREATE INDEX IDX_9A49B346A77FBEAF ON blog_post_gallery_image (blog_post_id)');
        $this->addSql('CREATE INDEX IDX_9A49B346828F7D6 ON blog_post_gallery_image (gallery_image_id)');
        $this->addSql('CREATE TABLE event_gallery_image (event_id INT NOT NULL, gallery_image_id INT NOT NULL, PRIMARY KEY (event_id, gallery_image_id))');
        $this->addSql('CREATE INDEX IDX_5F964D071F7E88B ON event_gallery_image (event_id)');
        $this->addSql('CREATE INDEX IDX_5F964D0828F7D6 ON event_gallery_image (gallery_image_id)');
        $this->addSql('CREATE TABLE event_participant (registered_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, role VARCHAR(100) DEFAULT NULL, attended BOOLEAN NOT NULL, notes TEXT DEFAULT NULL, event_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (event_id, user_id))');
        $this->addSql('CREATE INDEX IDX_7C16B89171F7E88B ON event_participant (event_id)');
        $this->addSql('CREATE INDEX IDX_7C16B891A76ED395 ON event_participant (user_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_event_participant ON event_participant (event_id, user_id)');
        $this->addSql('CREATE TABLE gallery_image (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, image VARCHAR(255) NOT NULL, title VARCHAR(255) NOT NULL, alt VARCHAR(500) NOT NULL, description TEXT DEFAULT NULL, visibility VARCHAR(20) NOT NULL, rgpd_consent BOOLEAN NOT NULL, consent_detail TEXT DEFAULT NULL, consented_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_published BOOLEAN NOT NULL, uploaded_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_21A0D47CA2B28FE8 ON gallery_image (uploaded_by_id)');
        $this->addSql('ALTER TABLE blog_post ADD CONSTRAINT FK_BA5AE01DF675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE blog_post_gallery_image ADD CONSTRAINT FK_9A49B346A77FBEAF FOREIGN KEY (blog_post_id) REFERENCES blog_post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE blog_post_gallery_image ADD CONSTRAINT FK_9A49B346828F7D6 FOREIGN KEY (gallery_image_id) REFERENCES gallery_image (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_gallery_image ADD CONSTRAINT FK_5F964D071F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_gallery_image ADD CONSTRAINT FK_5F964D0828F7D6 FOREIGN KEY (gallery_image_id) REFERENCES gallery_image (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event_participant ADD CONSTRAINT FK_7C16B89171F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE event_participant ADD CONSTRAINT FK_7C16B891A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE gallery_image ADD CONSTRAINT FK_21A0D47CA2B28FE8 FOREIGN KEY (uploaded_by_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE blog_post DROP CONSTRAINT FK_BA5AE01DF675F31B');
        $this->addSql('ALTER TABLE blog_post_gallery_image DROP CONSTRAINT FK_9A49B346A77FBEAF');
        $this->addSql('ALTER TABLE blog_post_gallery_image DROP CONSTRAINT FK_9A49B346828F7D6');
        $this->addSql('ALTER TABLE event_gallery_image DROP CONSTRAINT FK_5F964D071F7E88B');
        $this->addSql('ALTER TABLE event_gallery_image DROP CONSTRAINT FK_5F964D0828F7D6');
        $this->addSql('ALTER TABLE event_participant DROP CONSTRAINT FK_7C16B89171F7E88B');
        $this->addSql('ALTER TABLE event_participant DROP CONSTRAINT FK_7C16B891A76ED395');
        $this->addSql('ALTER TABLE gallery_image DROP CONSTRAINT FK_21A0D47CA2B28FE8');
        $this->addSql('DROP TABLE blog_post');
        $this->addSql('DROP TABLE blog_post_gallery_image');
        $this->addSql('DROP TABLE event_gallery_image');
        $this->addSql('DROP TABLE event_participant');
        $this->addSql('DROP TABLE gallery_image');
    }
}
